# Generated by Django 3.2.12 on 2022-03-22 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=50)),
                ('album_release_date', models.IntegerField()),
                ('album_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='bands.band')),
            ],
        ),
    ]
