# Generated by Django 3.2.12 on 2022-03-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('playlists', '0002_alter_playlist_user'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='songs_on_album',
            field=models.ManyToManyField(related_name='songs_on_album', through='songs.SongsOnAlbum', to='albums.Album'),
        ),
        migrations.AddField(
            model_name='song',
            name='songs_on_playlist',
            field=models.ManyToManyField(related_name='songs_on_playlist', through='songs.SongsOnPlaylist', to='playlists.Playlist'),
        ),
    ]
