# Generated by Django 3.2.12 on 2022-03-21 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=20)),
                ('artist_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('artist_age', models.IntegerField()),
                ('artist_nick', models.CharField(blank=True, max_length=30, null=True)),
                ('artist_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='bands.band')),
            ],
        ),
    ]
